---
openapi: 3.0.3
info:
  title: "tiger API"
  version: 2.0.1
paths:
  /bus/uk/woe/locations:
    get:
      operationId: "listWoELocations"
      parameters:
        - description: "Search Longitude & Latitude"
          name: "location"
          in: "query"
          required: false
          schema:
            type: "string"
      summary: "Get all available West of England stops"
      x-mojo-name: "list_woe_locations"
      x-mojo-to: "API::Bus::UK::WoE::Locations#list"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
          description: "West of England locations response"
  /bus/uk/woe/routes/{route_id}:
    get:
      operationId: "getWoERoutes"
      parameters:
        - description: "Internal route identifier"
          name: "route_id"
          in: "path"
          required: true
          schema:
            type: "string"
      summary: "Get data from West of England routes based on route id"
      x-mojo-name: "get_woe_routes"
      x-mojo-to: "API::Bus::UK::WoE::Routes#get"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
          description: "West of England routes response"
  /bus/uk/woe/services/{stop_id}:
    get:
      operationId: "getWoEServices"
      parameters:
        - description: "Internal stop identifier"
          name: "stop_id"
          in: "path"
          required: true
          schema:
            type: "string"
      summary: "Get data from West of England services based on stop id"
      x-mojo-name: "get_woe_services"
      x-mojo-to: "API::Bus::UK::WoE::Services#get"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
          description: "West of England services response"
  /hello_world:
    get:
      operationId: "getHelloWorld"
      summary: "Check the app uses to see if the API is running"
      x-mojo-name: "get_hello_world"
      x-mojo-to: "API::HelloWorld#list"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
          description: "Hello World response"
  /rail/uk/locations:
    get:
      operationId: "listRailLocations"
      summary: "Get all available locations on the Tiger CIS"
      x-mojo-name: "list_rail_locations"
      x-mojo-to: "API::Rail::UK::Locations#list"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "array"
          description: "Tiger CIS Locations response"
  /rail/uk/services/{tiploc_id}:
    get:
      operationId: "getRailServices"
      parameters:
        - description: "Internal TIPLOC identifier"
          name: "tiploc_id"
          in: "path"
          required: true
          schema:
            type: "string"
      summary: "Get data from Tiger CIS Services based on TIPLOC code"
      x-mojo-name: "get_rail_services"
      x-mojo-to: "API::Rail::UK::Services#get"
      responses:
        200:
          content:
            application/json:
              schema:
                type: "object"
          description: "Tiger CIS Services response"
servers:
- url: "/api/v1"

