#!/usr/bin/env perl
#   This file is part of tiger
#
#   Copyright 2025 PerplexedTheta
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
use strict;
use warnings;

use FindBin;
use lib ( "$FindBin::Bin/../../lib", "$FindBin::Bin/../../local/lib/perl5" );

use Getopt::Long qw( GetOptions );                                                                                      use Modern::Perl;

my $watch = 0;
GetOptions(
    "w|watch" => \$watch,
);

my $op = "css:build";
$op = "css:dev"
  if $watch;

system(qq{ cd "$FindBin::Bin/../.." && \$(which npx) gulp $op && exit 0 });

1;
