#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)" # get current script dir portibly

function bail () {
    rm -v -f "${SCRIPT_DIR}/payload.tgz"
    rm -v -f "${SCRIPT_DIR}/../../entrypoint.sh"
    exit 1
}

function write_env () {
    echo -ne "DOCKER_REGISTRY=ghcr.io\n" >"${SCRIPT_DIR}/.env" || return 1
    echo -ne "DOCKER_USERNAME=perplexedtheta\n" >>"${SCRIPT_DIR}/.env"
    echo -ne "DOCKER_PROJECT=tiger\n" >>"${SCRIPT_DIR}/.env"
}

function write_entrypoint () {
    cat <<EOF >"${SCRIPT_DIR}/../../entrypoint.sh"
#!/usr/bin/env bash

export MOJO_ADDR="[::]";

cd /tiger

carton install

/tiger/script/app
EOF

    chmod +x "${SCRIPT_DIR}/../../entrypoint.sh" || return 1
}

function write_css () {
    OLD_PWD="$(pwd)"
    cd "${SCRIPT_DIR}/../.."
    npm install --include=dev || return 1
    "${SCRIPT_DIR}/build_css_from_scss" || return 1
    cd "${OLD_PWD}"
}

function success () {
    rm -v -f "${SCRIPT_DIR}/payload.tgz"
    rm -v -f "${SCRIPT_DIR}/../../entrypoint.sh"
    exit 0
}

if [[ ! -f "${SCRIPT_DIR}/.env" ]]; then
    echo -ne "[INFO]\tNo .env file present - writing one. Edit it, set your values, and rerun this script\n"
    write_env
    bail
fi

. "${SCRIPT_DIR}/.env"

if [[ -z "${DOCKER_REGISTRY}" ]]; then
    echo -ne "[ERR]\tDOCKER_REGISTRY unset, please add it to your .env\n"
    bail
fi
if [[ -z "${DOCKER_USERNAME}" ]]; then
    echo -ne "[ERR]\DOCKER_USERNAME unset, please add it to your .env\n"
    bail
fi
if [[ -z "${DOCKER_PROJECT}" ]]; then
    echo -ne "[ERR]\DOCKER_PROJECT unset, please add it to your .env\n"
    bail
fi

write_css || bail

write_entrypoint || bail
cd "${SCRIPT_DIR}/../.."

tar --exclude=./.git \
    --exclude=./.gitignore \
    --exclude=./cpanfile.snapshot \
    --exclude=./Dockerfile \
    --exclude=./local \
    --exclude=./node_modules \
    --exclude=./package-lock.json \
    --exclude=./script/devel \
    --exclude=./t \
    -cvf - . \
| \
gzip -9 >"${SCRIPT_DIR}/payload.tgz" || bail

DIST=noble
TAG="${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${DOCKER_PROJECT}:${DIST}"
PLATFORM="linux/amd64,linux/arm64"

echo -ne "[INFO]\tBuilding for ${DIST} on ${PLATFORM}\n"
docker buildx build --platform ${PLATFORM} -t ${TAG} . || bail
echo -ne "[INFO]\tSuccess! Tagged as ${TAG}\n"

success
