#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib ( "$FindBin::Bin/../lib", "$FindBin::Bin/../local/lib/perl5" );
use Mojolicious::Commands;

## start command line interface for application
my $c = Mojolicious::Commands->new;

## detect and then set env
$c->detect;
$ENV{'MOJO_CONF'}  ||= "$FindBin::Bin/../tiger.yml";
$ENV{'MOJO_PROTO'} ||= 'http';
$ENV{'MOJO_PORT'}  ||= 3000;

## run app
$c->start_app( 'Tiger', 'daemon', '-l', $ENV{'MOJO_PROTO'} . '://*:' . $ENV{'MOJO_PORT'} );
